NAME = libft.a

SRCS = ft_isalpha.c ft_isdigit.c ft_isalnum.c ft_isascii.c ft_isprint.c ft_strlen.c \
       ft_memset.c ft_bzero.c ft_memcpy.c ft_memmove.c ft_strlcpy.c \
       ft_strlcat.c ft_toupper.c ft_tolower.c ft_strchr.c ft_strrchr.c \
       ft_strncmp.c ft_memchr.c ft_memcmp.c ft_strnstr.c ft_atoi.c ft_calloc.c ft_strdup.c \
       ft_substr.c ft_strjoin.c ft_strtrim.c ft_split.c ft_itoa.c ft_strmapi.c \
       ft_striteri.c ft_putchar_fd.c ft_putstr_fd.c ft_putendl_fd.c ft_putnbr_fd.c \
	   get_next_line.c get_next_line_utils.c \
	   ft_printf.c ft_hexa.c ft_ptr.c print_type.c ft_utoa.c ft_printf_utils.c

BONUS = ft_lstnew_bonus.c ft_lstadd_front_bonus.c ft_lstsize_bonus.c ft_lstlast_bonus.c \
		ft_lstadd_back_bonus.c ft_lstdelone_bonus.c ft_lstclear_bonus.c ft_lstiter_bonus.c \
		ft_lstmap_bonus.c get_next_line_utils_bonus.c get_next_line_bonus.c

OBJS_BONUS = ${BONUS:.c=.o}

OBJS = ${SRCS:.c=.o}

CC		= cc

RM		= rm -f

CFLAGS = -Wall -Wextra -Werror

.c.o:
		@${CC} ${CFLAGS} -c $< -o ${<:.c=.o}

$(NAME): ${OBJS}
		@ar rcs ${NAME} ${OBJS}
		@ranlib ${NAME}

all:	${NAME}

clean:
		@${RM} ${OBJS} ${OBJS_BONUS}

fclean:	clean
		@${RM} ${NAME}

re:		fclean all

bonus:	 ${OBJS_BONUS}
		@ar rcs ${NAME} ${OBJS_BONUS}
		@ranlib ${NAME}

comp:
	cc -Wall -Werror -Wextra -L. -lft main.c

.PHONY: all clean fclean re
